#!/bin/sh

set -e

# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="/usr/local/bin:$PATH"

SCRIPT_DIR=$(dirname "$0")
pushd "$SCRIPT_DIR/.." > /dev/null
ROOT_PATH="$PWD"
popd > /dev/null

${SCRIPT_DIR}/update_libssh2
${SCRIPT_DIR}/update_curl

echo "Building libgit2"

LIBSSH_DIR="${ROOT_PATH}/External/libssh2"
LIBSSL_DIR="${ROOT_PATH}/External/openssl/bin"
CURL_DIR="${ROOT_PATH}/External/curl/bin"

product="libgit2.a"
install_path="${ROOT_PATH}/External/${product}"

rm -f "$install_path"
cd "${ROOT_PATH}/External/libgit2"

if [ -d "build" ]; then
    rm -rf "build"
fi

mkdir build
cd build

export PKG_CONFIG_PATH=${LIBSSH_DIR}/bin/lib/pkgconfig:${LIBSSL_DIR}/lib/pkgconfig:${CURL_DIR}/lib/pkgconfig:$PKG_CONFIG_PATH
export CMAKE_INCLUDE_PATH="${LIBSSH_DIR}/include"
export CMAKE_LIBRARY_PATH="${LIBSSH_DIR}/bin/lib"
cmake -DBUILD_SHARED_LIBS:BOOL=OFF \
	-DLIBSSH2_INCLUDE_DIRS:PATH=${LIBSSH_DIR}/include/ \
    -DBUILD_CLAR:BOOL=OFF \
    -DTHREADSAFE:BOOL=ON \
	-DOPENSSL_CRYPTO_PATH=${LIBSSL_DIR}/lib \
    -DLIBSSH2_PATH=${LIBSSH_DIR}/bin/lib \
	-DZLIB_PATH=/usr/lib \
    ..
cmake --build .

if [ "${product}" -nt "${install_path}" ]; then
    cp -v "${product}" "${install_path}"
fi

echo "libgit2 has been updated."
