#!/bin/sh

set -e

# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="/usr/local/bin:$PATH"

product="libgit2.a"
home=`pwd`
install_path="${home}/External/${product}"

rm -f "$install_path"
cd "External/libgit2"

if [ -d "build" ]; then
    rm -rf "build"
fi

mkdir build
cd build

export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
cmake -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DLIBSSH2_INCLUDE_DIRS:PATH=/usr/local/include/ \
    -DBUILD_CLAR:BOOL=OFF \
    -DTHREADSAFE:BOOL=ON \
    ..
cmake --build .

if [ "${product}" -nt "${install_path}" ]; then
    cp -v "${product}" "${install_path}"
fi

echo "libgit2 has been updated."
